### ISSUE TITLE
With new plugin support gitbucket should support accessing the internet using a proxy

### ISSUE THREAD

**Issue by simula67** [takezoe/gitbucket#497]
Running gitbucket gives the following error on command line : 

org.eclipse.jgit.api.errors.TransportException: https://github.com/takezoe/gitbucket_plugins.git: cannot open git-upload-pack
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at plugin.PluginUpdateJob$$anonfun$execute$1.apply(PluginUpdateJob.scala:36) ~[classes/:na]
        at plugin.PluginUpdateJob$$anonfun$execute$1.apply(PluginUpdateJob.scala:27) ~[classes/:na]
        at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.2.jar:na]
        at plugin.PluginUpdateJob.execute(PluginUpdateJob.scala:27) ~[classes/:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:na]
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/takezoe/gitbucket_plugins.git: cannot open git-upload-pack
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:521) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:309) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        ... 8 common frames omitted
Caused by: java.net.ConnectException: Connection timed out github.com
        at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:175) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:475) ~[org.eclipse.jgit-3.4.1.201406201815-r.jar:3.4.1.201406201815-r]
        ... 13 common frames omitted

I tried running with the following command : 
$GITBUCKET_DIR/jre_linux_x64/bin/java -jar $GITBUCKET_DIR/gitbucket.war -DproxySet=true  -DproxyHost=proxy.example.com -DproxyPort=8080 --port=8081 --gitbucket.home=$GITBUCKET_DIR/data

Still shows the same error.

**Comment by Kuchitama** [comment]
I made a patch to support proxy setting for v2.7.
https://github.com/Kuchitama/gitbucket/tree/v2.7_with_proxy
If we can use git bucket under a proxy, we run gitbucket with options  `-Dhttp.proxyHost=<proxy_host> -Dhttp.proxyPort=<proxy_port>`.

@takezoe 
Will you change the plugin system at next version?
I can't make a pull request because any codes about plugins are deleted.

**Comment by takezoe** [comment]
Plugin system has been renewed in GitBucket 3.0. The current plugin system does not support plugin installation via internet.

**Comment by Kuchitama** [comment]
:+1:
