### ISSUE TITLE
Failed to view binary files

### ISSUE THREAD

**Issue by ysksuzuki** [takezoe/gitbucket#534]
I can't view binary files whose size exceed 1MB such as pdf or mp4 on repository viewer. The following error occurs.

I found the following source code that checks wheter the file size is over 1MB. 
https://github.com/takezoe/gitbucket/blob/master/src/main/scala/util/FileUtil.scala#L31

I want to change that limit size with system setting or any other way.
Any plan?

Here is the error message.

```
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:322)
	at scala.None$.get(Option.scala:320)
	at app.RepositoryViewerControllerBase$$anonfun$16$$anonfun$apply$22$$anonfun$apply$23$$anonfun$apply$24.apply(RepositoryViewerController.scala:198)
	at app.RepositoryViewerControllerBase$$anonfun$16$$anonfun$apply$22$$anonfun$apply$23$$anonfun$apply$24.apply(RepositoryViewerController.scala:195)
	at scala.Option.map(Option.scala:145)
	at app.RepositoryViewerControllerBase$$anonfun$16$$anonfun$apply$22$$anonfun$apply$23.apply(RepositoryViewerController.scala:195)
	at app.RepositoryViewerControllerBase$$anonfun$16$$anonfun$apply$22$$anonfun$apply$23.apply(RepositoryViewerController.scala:192)
	at util.ControlUtil$.using(ControlUtil.scala:26)
	at app.RepositoryViewerControllerBase$$anonfun$16$$anonfun$apply$22.apply(RepositoryViewerController.scala:192)
	at app.RepositoryViewerControllerBase$$anonfun$16$$anonfun$apply$22.apply(RepositoryViewerController.scala:188)
	at util.ReferrerAuthenticator$$anonfun$util$ReferrerAuthenticator$$authenticate$1$$anonfun$apply$12.apply(Authenticator.scala:123)
	at util.ReferrerAuthenticator$$anonfun$util$ReferrerAuthenticator$$authenticate$1$$anonfun$apply$12.apply(Authenticator.scala:121)
	at scala.Option.map(Option.scala:145)
	at util.ReferrerAuthenticator$$anonfun$util$ReferrerAuthenticator$$authenticate$1.apply(Authenticator.scala:121)
	at util.ReferrerAuthenticator$$anonfun$util$ReferrerAuthenticator$$authenticate$1.apply(Authenticator.scala:120)
	at util.ControlUtil$.defining(ControlUtil.scala:14)
	at util.ReferrerAuthenticator$class.util$ReferrerAuthenticator$$authenticate(Authenticator.scala:120)
	at util.ReferrerAuthenticator$class.referrersOnly(Authenticator.scala:115)
	at app.RepositoryViewerController.referrersOnly(RepositoryViewerController.scala:22)
	at app.RepositoryViewerControllerBase$$anonfun$16.apply(RepositoryViewerController.scala:188)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)
	at app.ControllerBase.withRouteMultiParams(ControllerBase.scala:21)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)

...
```

**Comment by ynnuyonw** [comment]
My question is this, I need this feature, but how to configure it！

**Comment by takezoe** [comment]
@ynnuyonw OK, Can I merge #588 to this issue?

**Comment by emag** [comment]
:+1:
