### ISSUE TITLE
Notification fails w/ "session closed" for comments containing at-mentions

### ISSUE THREAD

**Issue by jcracknell** [takezoe/gitbucket#571]
Presumably this will also fail for `issue:` mentions.

```
10:15:54.638 [ForkJoinPool-1-worker-1] ERROR util.Mailer - Notifications Failed.
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-180]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.180.jar:1.4.180]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.180.jar:1.4.180]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.180.jar:1.4.180]
	at org.h2.engine.Session.prepareLocal(Session.java:424) ~[h2-1.4.180.jar:1.4.180]
	at org.h2.engine.Session.prepareCommand(Session.java:388) ~[h2-1.4.180.jar:1.4.180]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189) ~[h2-1.4.180.jar:1.4.180]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72) ~[h2-1.4.180.jar:1.4.180]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:666) ~[h2-1.4.180.jar:1.4.180]
	at scala.slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:152) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:389) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:32) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.Invoker$class.firstOption(Invoker.scala:29) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16) ~[slick_2.11-2.1.0.jar:na]
	at service.AccountService$class.getAccountByUserName(AccountService.scala:78) ~[classes/:na]
	at view.GitBucketHtmlSerializer.service$RequestCache$$super$getAccountByUserName(Markdown.scala:88) ~[classes/:na]
	at service.RequestCache$$anonfun$getAccountByUserName$1.apply(RequestCache.scala:27) ~[classes/:na]
	at service.RequestCache$$anonfun$getAccountByUserName$1.apply(RequestCache.scala:27) ~[classes/:na]
	at app.Context$$anonfun$cache$1$$anonfun$apply$1.apply(ControllerBase.scala:158) ~[classes/:na]
	at scala.Option.getOrElse(Option.scala:120) ~[scala-library-2.11.2.jar:na]
	at app.Context$$anonfun$cache$1.apply(ControllerBase.scala:157) ~[classes/:na]
	at app.Context$$anonfun$cache$1.apply(ControllerBase.scala:156) ~[classes/:na]
	at util.ControlUtil$.defining(ControlUtil.scala:14) ~[classes/:na]
	at app.Context.cache(ControllerBase.scala:156) ~[classes/:na]
	at service.RequestCache$class.getAccountByUserName(RequestCache.scala:26) ~[classes/:na]
	at view.GitBucketHtmlSerializer.getAccountByUserName(Markdown.scala:88) ~[classes/:na]
	at view.LinkConverter$$anonfun$convertRefsLinks$2.apply(LinkConverter.scala:27) ~[classes/:na]
	at view.LinkConverter$$anonfun$convertRefsLinks$2.apply(LinkConverter.scala:26) ~[classes/:na]
	at util.Implicits$RichString$$anonfun$replaceBy$1.apply(Implicits.scala:40) ~[classes/:na]
	at util.Implicits$RichString$$anonfun$replaceBy$1.apply(Implicits.scala:37) ~[classes/:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[scala-library-2.11.2.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1177) ~[scala-library-2.11.2.jar:na]
	at util.Implicits$RichString.replaceBy(Implicits.scala:37) ~[classes/:na]
	at view.LinkConverter$class.convertRefsLinks(LinkConverter.scala:26) ~[classes/:na]
	at view.GitBucketHtmlSerializer.convertRefsLinks(Markdown.scala:88) ~[classes/:na]
	at view.GitBucketHtmlSerializer.visit(Markdown.scala:155) ~[classes/:na]
	at org.pegdown.ast.TextNode.accept(TextNode.java:51) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:365) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:348) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:365) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:377) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:162) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:365) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:91) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ast.RootNode.accept(RootNode.java:51) ~[pegdown-1.4.1.jar:1.4.1]
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:72) ~[pegdown-1.4.1.jar:1.4.1]
	at view.Markdown$.toHtml(Markdown.scala:38) ~[classes/:na]
	at util.Mailer$$anonfun$1$$anonfun$apply$4$$anonfun$apply$5.apply(Notifier.scala:77) ~[classes/:na]
	at util.Mailer$$anonfun$1$$anonfun$apply$4$$anonfun$apply$5.apply(Notifier.scala:74) ~[classes/:na]
	at scala.Option.foreach(Option.scala:245) ~[scala-library-2.11.2.jar:na]
	at util.Mailer$$anonfun$1$$anonfun$apply$4.apply(Notifier.scala:74) ~[classes/:na]
	at util.Mailer$$anonfun$1$$anonfun$apply$4.apply(Notifier.scala:73) ~[classes/:na]
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34) ~[slick_2.11-2.1.0.jar:na]
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61) ~[slick_2.11-2.1.0.jar:na]
	at util.Mailer$$anonfun$1.apply(Notifier.scala:73) ~[classes/:na]
	at util.Mailer$$anonfun$1.apply(Notifier.scala:72) ~[classes/:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
```

**Comment by takezoe** [comment]
I think this problem was already fixed.
