### ISSUE TITLE
All issues are not checked

### ISSUE THREAD

**Issue by ssogabe** [takezoe/gitbucket#632]
Gitbucket head

## Steps to reproduce

1.  go to issues page.
2.  click the checkbox in the header (see blow).

## Actual result

 No issues checked

## Expected result

 All issues checked

![image](https://cloud.githubusercontent.com/assets/271370/6323384/5543363c-bb6c-11e4-8fa1-edafd23b6543.png)

and if you click the checkbox in the header and click the label dropdown. then you can get the following exception.

```
java.lang.NumberFormatException: For input string: "on"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:241)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:30)
	at app.IssuesControllerBase$$anonfun$app$IssuesControllerBase$$executeBatch$1.apply(IssuesController.scala:308)
	at app.IssuesControllerBase$$anonfun$app$IssuesControllerBase$$executeBatch$1.apply(IssuesController.scala:308)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at app.IssuesControllerBase$class.app$IssuesControllerBase$$executeBatch(IssuesController.scala:308)
	at app.IssuesControllerBase$$anonfun$24$$anonfun$apply$64$$anonfun$apply$65.apply(IssuesController.scala:267)
	at app.IssuesControllerBase$$anonfun$24$$anonfun$apply$64$$anonfun$apply$65.apply(IssuesController.scala:266)
	at scala.Option.map(Option.scala:145)
	at app.IssuesControllerBase$$anonfun$24$$anonfun$apply$64.apply(IssuesController.scala:266)
	at app.IssuesControllerBase$$anonfun$24$$anonfun$apply$64.apply(IssuesController.scala:265)
	at util.CollaboratorsAuthenticator$$anonfun$util$CollaboratorsAuthenticator$$authenticate$1$$anonfun$apply$9.apply(Authenticator.scala:100)
	at util.CollaboratorsAuthenticator$$anonfun$util$CollaboratorsAuthenticator$$authenticate$1$$anonfun$apply$9.apply(Authenticator.scala:98)
	at scala.Option.map(Option.scala:145)
	at util.CollaboratorsAuthenticator$$anonfun$util$CollaboratorsAuthenticator$$authenticate$1.apply(Authenticator.scala:98)
	at util.CollaboratorsAuthenticator$$anonfun$util$CollaboratorsAuthenticator$$authenticate$1.apply(Authenticator.scala:97)
	at util.ControlUtil$.defining(ControlUtil.scala:14)
	at util.CollaboratorsAuthenticator$class.util$CollaboratorsAuthenticator$$authenticate(Authenticator.scala:97)
	at util.CollaboratorsAuthenticator$class.collaboratorsOnly(Authenticator.scala:92)
	at app.IssuesController.collaboratorsOnly(IssuesController.scala:13)
	at app.IssuesControllerBase$$anonfun$24.apply(IssuesController.scala:265)

(snip)
```

**Comment by ssogabe** [comment]
pull requests (/pulls) has same issue.
