### ISSUE TITLE
JettyLauncher : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by meduz** [takezoe/gitbucket#633]
following instructions on 
http://www.debian-administration.org/article/710/Setting_up_your_own_graphical_git-server_with_gitbucket

to install on a debian server, I stumble on:

````
lolo@rem:~$ java -jar gitbucket.war
Exception in thread "main" java.lang.UnsupportedClassVersionError: JettyLauncher : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: JettyLauncher. Program will exit.
lolo@rem:~$
````

I tried installing and launching jetty:

````
129  aptitude search Jetty
130  sudo aptitude install jetty
131  sudo vi /etc/default/jetty
132  sudo /etc/init.d/jetty status
133  sudo /etc/init.d/jetty start
137  sudo aptitude install libjetty-extra
````

but no success.

**Comment by takezoe** [comment]
```
Unsupported major.minor version 51.0
```

This message means GitBucket requires Java7 or higher. What version of Java are you using? You can check your Java version by `java -version`.

**Comment by meduz** [comment]
Thanks for the answer.

I was following the instructions on

http://www.debian-administration.org/article/710/Setting_up_your_own_graphical_git-server_with_gitbucket

such that I use 

````
  sudo aptitude install icedtea-7-jre-cacao
  sudo aptitude install icedtea-7-jre-jamvm

````

maybe this package provides a bad version

````
    $ java -version
    java version "1.6.0_34"
    OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1~deb7u1)
    OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

````

**Comment by takezoe** [comment]
Your active JDK is Java6. Use Java7 or later.
