### ISSUE TITLE
Any information on how to setup 'GitHub pull request builder plugin'

### ISSUE THREAD

**Issue by tune** [takezoe/gitbucket#684]
I've tried to setup Jenkins 'GitHub pull request builder plugin'.
But it doesn't work yet.
I'd like to know the correct setting.

In my environment, gitbucket is runnning under subdirectory like 'http://example.com/gitbucket'.

-----

#### Q1: 'GitHub server api URL' in system setting page.

I guess this field should be 'http://example.com/gitbucket/api/v3/'

#### Q2: 'GitHub project' in job setting page

It seems Gprb plugin use this field for retrieving repository information.

 When I set 'http://example.com/gitbucket/group/sample', Gprb access 'http://example.com/gitbucket/api/v3/repos/gitbucket/group' URL.

 When I set 'http://example.com/group/sample', Gprb access 'http://example.com/gitbucket/api/v3/repos/group/sample' URL.

 In both case, gitbucket return simple JSON data, {"message":"Not Found"}.

**Comment by nazoking** [comment]
1. install jenkins with GitHub pull request builder plugin as `http://jenkins:9090/`
  2. install gitbucket as `http://gitbucket:8080/`
  3. create repository on gitbucket as `http://gitbucket:8080/root/repo1`
  4. set webhook setting `http://jenkins:9090/ghprbhook/`
  5. create personal access token on `http://gitbucket:8080/root/_application` ( root is user has permission to root/repo1 )
  6. set jenkins global setting of GitHub Pull Request Builder on `http://jenkins:9090/manage`
    * GitHub server api URL = `http://gitbucket:8080/api/v3`
    * Access Token = created on step 5.
    * Save.
  7. create job as `http://jenkins:9090/job/testjob/`
  8. on http://jenkins:9090/job/testjob/configure,
    * GitHub project = `http://gitbucket:8080/root/test/`
    * Source Code Management
      * git
        * Repositories
          * Repository URL = `http://gitbucket:8080/git/root/test.git`
          * Refspec = `+refs/pull/*:refs/remotes/origin/pr/*`
        * Branches to build
          * Branch Specifier (blank for 'any') = `${sha1}`
    * Build trigger
      * GitHub Pull Request Builder
        * Admin list = `root`
    * Save.

  9. hint
   * jenkins log has a lot information that show on `http://jenkins:9090/log/all` .
   * user that create access token has permission to write repository ?
   * when you replace access token, but jenkins not use soon. please restart jenkins.

**Comment by takezoe** [comment]
@nazoking Great introduction! Can I copy this to Wiki?

**Comment by nazoking** [comment]
( I rewriete some repository url now .. )
@takezoe thanks please copy it.

**Comment by takezoe** [comment]
@nazoking Thanks! I copied to Wiki. If you have any additional information, please update Wiki directly.
https://github.com/takezoe/gitbucket/wiki/Setup-Jenkins-GitHub-pull-request-builder-plugin

@tune Does this introduction help you?

**Comment by tune** [comment]
Following error message is recorded in Jenkins.
I'm wondering why my gitbucket return "Not Found" message.

```txt
3 31, 2015 8:37:00 午前 重大 org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
Could not retrieve GitHub repository named group/sample (Do you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: {"message":"Not Found"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:491)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:320)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:66)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:76)
	at org.jenkinsci.plugins.ghprb.Ghprb.run(Ghprb.java:101)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:149)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:265)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: http://example.com/gitbucket/api/v3/repos/group/sample
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 16 more
Caused by: java.io.FileNotFoundException: http://example.com/gitbucket/api/v3/repos/group/sample
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 17 more
```

**Comment by takezoe** [comment]
@tune #691 has been released in 3.1.1. Could you try it?

**Comment by tune** [comment]
It works. Thank you! :+1:

**Comment by tune** [comment]
In my environment, Jenkins bot start to comment on PullRequest page.

But it never start build tasks, always ask 'Can one of the admins verify this patch?'
It doesn't work though I comment 'ok to test' or though I set admin/whitelist.

I'm afraid another gitbucket API is not working correctly when gitbucket is working under sub-directory path.
Referring the commit d120142, it only affect '/api/v3/repos' API.
Is there other API that need to fix in same way?

-----

プルリクエストにコメントは残るようになりましたが、ビルドタスクが走りません。
コメント/Admin/Whitelistいずれにも反応しないことから、Gitbucketからユーザ名を正しく取得していない可能性を疑っています。
修正いただいたd120142のコミットは'/api/v3/repos'のみを対応していましたが、他のAPIも http://example.com/gitbucket のようなパスで動作させると動かないケースはありませんでしょうか?

**Comment by nazoking** [comment]
I found some bugs.
Probably, It dose not cause by context-path.
The `user` of issue_comment webhook's payload , indicate repository owner now. Its correct value indecate commentedUser.

**Comment by tunepolo** [comment]
It seems problem still exists, URL that includes user account is not set properly.

I'm using 'tune' account with 'Yuichi Tsunematsu' full name setting.
Gitbucket use 'Yuichi Tsunematsu' instead of 'tune'.

When I access to 'http://example.com/gitbucket/api/v3/users/tune' URL, gitbucket return following JSON.

```json
{
  "login": "Yuichi Tsunematsu",
  "email": "tunepolo@gmail.com",
  "type": "User",
  "site_admin": true,
  "created_at": "2014-01-06T04:29:11Z",
  "url": "http://example.com/gitbucket/api/v3/users/Yuichi Tsunematsu",
  "html_url": "http://example.com/gitbucket/Yuichi Tsunematsu"
}
```

Above JSON should be

```json
{
  "login": "Yuichi Tsunematsu",
  "email": "tunepolo@gmail.com",
  "type": "User",
  "site_admin": true,
  "created_at": "2014-01-06T04:29:11Z",
  "url": "http://example.com/gitbucket/api/v3/users/tune",
  "html_url": "http://example.com/gitbucket/tune"
}
```

**Comment by tunepolo** [comment]
Finally it works with Gitbucket v3.3 :-)
