### ISSUE TITLE
Can't load index page

### ISSUE THREAD

**Issue by darkweaver87** [takezoe/gitbucket#715]
Hello,

Since few days I can't load the index page. Instead I have this java exception:

java.lang.IllegalArgumentException: named capturing group is missing trailing '}'
	at java.util.regex.Matcher.appendReplacement(Matcher.java:792)
	at scala.util.matching.Regex$Replacement$class.replace(Regex.scala:804)
	at scala.util.matching.Regex$MatchIterator$$anon$1.replace(Regex.scala:782)
	at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
	at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.util.matching.Regex.replaceAllIn(Regex.scala:473)
	at gitbucket.core.view.helpers$RegexReplaceString.replaceAll(helpers.scala:151)
	at gitbucket.core.view.helpers$.activityMessage(helpers.scala:164)
	at gitbucket.core.helper.html.activities$.gitbucket$core$helper$html$activities$$simpleActivity$1(activities.template.scala:49)
	at gitbucket.core.helper.html.activities$$anonfun$apply$1.apply(activities.template.scala:72)
	at gitbucket.core.helper.html.activities$$anonfun$apply$1.apply(activities.template.scala:59)
	at scala.collection.immutable.List.map(List.scala:277)
	at gitbucket.core.helper.html.activities$.apply(activities.template.scala:59)
	at gitbucket.core.html.index$.apply(index.template.scala:28)
	at gitbucket.core.controller.IndexControllerBase$$anonfun$2.apply(IndexController.scala:31)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)
	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:88)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:82)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237)
	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:30)
	at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:27)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:27)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

Since this I upgraded from 2.8 to 3.1 just to see if it change something but it's still the same.

Thanks in advance for your help.

Rémi

**Comment by takezoe** [comment]
Do tags or branches recently you added contain some special characters?

**Comment by darkweaver87** [comment]
Hello,

Yes one of my users created a tag named 'release-${project.version}'.

Rémi

**Comment by takezoe** [comment]
@darkweaver87 Thanks. I could reproduce this issue and it will be fixed in the next release 3.2.

**Comment by darkweaver87** [comment]
Great :-) Many thanks.
