### ISSUE TITLE
i got a "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by losper** [takezoe/gitbucket#721]
hi,i finded a bug in gitbucket 3.1.1 & win7.
i pushed my code into server,and i viewed the code on the server,i  got this result.plz tell me how can i do?
java.lang.NullPointerException
	at org.eclipse.jgit.util.RawParseUtils.commitMessage(RawParseUtils.java:1024)
	at org.eclipse.jgit.revwalk.RevCommit.getFullMessage(RevCommit.java:440)
	at gitbucket.core.util.JGitUtil$$anonfun$getFileList$1$$anonfun$apply$11.apply(JGitUtil.scala:303)
	at gitbucket.core.util.JGitUtil$$anonfun$getFileList$1$$anonfun$apply$11.apply(JGitUtil.scala:298)
	at scala.collection.immutable.List.map(List.scala:273)
	at gitbucket.core.util.JGitUtil$$anonfun$getFileList$1.apply(JGitUtil.scala:298)
	at gitbucket.core.util.JGitUtil$$anonfun$getFileList$1.apply(JGitUtil.scala:199)
	at gitbucket.core.util.ControlUtil$.using(ControlUtil.scala:35)
	at gitbucket.core.util.JGitUtil$.getFileList(JGitUtil.scala:199)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$gitbucket$core$controller$RepositoryViewerControllerBase$$fileList$1$$anonfun$apply$75$$anonfun$apply$76.apply(RepositoryViewerController.scala:509)
	...

**Comment by nazoking** [comment]
umm.. perhaps, a cause is jgit bug.

can you test [this war (gitbucket 3.1.1 + jgit 3.7.0.201502260915-r )](https://dl.dropboxusercontent.com/u/196431/gitbucket.war)?

or if you can push it repository to reachable place from me, I can clone and test it.

**Comment by losper** [comment]
@nazoking 
i've pushed this repository to "http://gitbucket.herokuapp.com/zhujiuwen/media_file_agent"
plz test it,thank you!

**Comment by losper** [comment]
@nazoking 
i've tested this war (gitbucket 3.1.1 + jgit 3.7.0.201502260915-r ),
but got "org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index"
ps.i've pushed this repository to https://github.com/losper/media_file_agent
please test it,thank you!

**Comment by nazoking** [comment]
@losper thanks you reporting. I found it condition and fixed on https://github.com/takezoe/gitbucket/pull/723

**Comment by takezoe** [comment]
Fixed in #723

**Comment by losper** [comment]
@nazoking good job!
