### ISSUE TITLE
NullPointerException on MainPage after PC-Crash

### ISSUE THREAD

**Issue by dernerv** [takezoe/gitbucket#733]
After a PC-Crash, i got the following NullPointerException on the MainPage after Login.
Repository sites are working and access them via git is also still possible.

org.h2.jdbc.JdbcSQLException: Eingabe/Ausgabe: "java.io.IOException: java.lang.NullPointerException"; "lob: null table: 58 id: 70"
IO Exception: "java.io.IOException: java.lang.NullPointerException"; "lob: null table: 58 id: 70" [90031-180]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convertIOException(DbException.java:330)
	at org.h2.value.ValueLobDb.getString(ValueLobDb.java:302)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:285)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:934)
	at scala.slick.driver.JdbcTypesComponent$JdbcTypes$StringJdbcType.getValue(JdbcTypesComponent.scala:203)
	at scala.slick.driver.JdbcTypesComponent$JdbcTypes$StringJdbcType.getValue(JdbcTypesComponent.scala:200)
	at scala.slick.jdbc.SpecializedJdbcResultConverter$$anon$2.read(SpecializedJdbcResultConverters.scala:45)
	at scala.slick.jdbc.SpecializedJdbcResultConverter$$anon$2.read(SpecializedJdbcResultConverters.scala:43)
	at scala.slick.relational.ProductResultConverter.read(ResultConverter.scala:56)
	at scala.slick.relational.ProductResultConverter.read(ResultConverter.scala:46)
	at scala.slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:125)
	at scala.slick.driver.JdbcInvokerComponent$QueryInvoker.extractValue(JdbcInvokerComponent.scala:42)
	at scala.slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:63)
	at scala.slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
	at scala.slick.util.ReadAheadIterator$class.scala$slick$util$ReadAheadIterator$$update(ReadAheadIterator.scala:34)
	at scala.slick.util.ReadAheadIterator$class.hasNext(ReadAheadIterator.scala:40)
	at scala.slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:65)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.build(Invoker.scala:47)
	at scala.slick.jdbc.StatementInvoker.build(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.list(Invoker.scala:39)
	at scala.slick.jdbc.StatementInvoker.list(StatementInvoker.scala:16)
	at gitbucket.core.service.ActivityService$class.getRecentActivitiesByOwners(ActivityService.scala:41)
	at gitbucket.core.controller.IndexController.getRecentActivitiesByOwners(IndexController.scala:14)
	at gitbucket.core.controller.IndexControllerBase$$anonfun$2.apply(IndexController.scala:42)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)
	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:88)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:82)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237)
	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:30)
	at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:27)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:27)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.h2.message.DbException.convertToIOException(DbException.java:364)
	at org.h2.util.IOUtils.copyAndCloseInput(IOUtils.java:213)
	at org.h2.util.IOUtils.readStringAndClose(IOUtils.java:307)
	at org.h2.value.ValueLobDb.getString(ValueLobDb.java:292)
	... 164 more
Caused by: java.lang.NullPointerException
	at org.h2.mvstore.StreamStore$Stream.nextBuffer(StreamStore.java:453)
	at org.h2.mvstore.StreamStore$Stream.read(StreamStore.java:414)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read1(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at org.h2.util.IOUtils.copyAndCloseInput(IOUtils.java:200)
	... 166 more

**Comment by takezoe** [comment]
It seems H2 data is broken. The recover tool might help you.
http://www.h2database.com/html/advanced.html#using_recover_tool

**Comment by dernerv** [comment]
Thank you, after some work i was able to recover the Activity table.
To the problem itself, at crash time there was no activity on the gitbucket
service.
So i ask myself, how could this inconsistency happen. Is it a H2 database
problem or
was the transaction not finished?

Again thank you and great work.
Steffen

2015-04-29 18:41 GMT+02:00 Naoki Takezoe <notifications@github.com>:

**Comment by takezoe** [comment]
It's a difficult question.
I don't know internal details of H2. However, H2 is not a database which provides high reliability essentially. I think it's a tradeoff of easiness and reliability.

**Comment by takezoe** [comment]
Already resolved.
