### ISSUE TITLE
java.lang.AbstractMethodError: Plugin.initialize

### ISSUE THREAD

**Issue by Prajithp** [takezoe/gitbucket#754]
I tried to update the gitbucket to latest 3.2 build, but I'm getting  following errors. 
```
2015-05-11 06:41:10.639:WARN:oejuc.AbstractLifeCycle:FAILED o.e.j.w.WebAppContext{/,file:/opt/gitbucket/data/tmp/webapp/},file:/opt/gitbucket/lib/gitbucket.war: java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
        at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:123)
        at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:98)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:98)
        at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:41)
        at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:30)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:282)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at JettyLauncher.main(JettyLauncher.java:65)
2015-05-11 06:41:10.641:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@63070bab: java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
        at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:123)
        at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:98)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:98)
        at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:41)
        at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:30)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:282)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at JettyLauncher.main(JettyLauncher.java:65)
Exception in thread "main" java.lang.AbstractMethodError: Plugin.initialize(Lgitbucket/core/plugin/PluginRegistry;Ljavax/servlet/ServletContext;Lgitbucket/core/service/SystemSettingsService$SystemSettings;)V
        at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:123)
        at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:98)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:98)
        at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:41)
        at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.scala:30)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:282)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at JettyLauncher.main(JettyLauncher.java:65)
```

3.1 was also throwing same errors.

**Comment by takezoe** [comment]
This problem has been already fixed in https://github.com/takezoe/gitbucket-gist-plugin/pull/4/files. Build a gitbucket-gist-plugin from the latest source code again and replace `~/.gitbucket/plugins/gitbucket-gist-plugin_2.11-x.x.jar`.
