### ISSUE TITLE
org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Unsynchronized metadata read [1.4.180/3]"; SQL statement:

### ISSUE THREAD

**Issue by Prajithp** [takezoe/gitbucket#756]
Gitbucket  home page is not loading and I see trace below.
```
org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Unsynchronized metadata read [1.4.180/3]"; SQL statement:
select x2.x3, x2.x4, x2.x5, x2.x6, x2.x7, x2.x8, x2.x9, x2.x10 from (select x11.x12 as x9, x11.x13 as x6, x11.x14 as x5, x11.x15 as x4, x11.x16 as x8, x11.x17 as x10, x11.x18 as x3, x11.x19 as x7 from (select x20."ACTIVITY_DATE" as x12, x20."ACTIVITY_TYPE" as x13, x20."ACTIVITY_USER_NAME" as x14, x20."REPOSITORY_NAME" as x15, x20."ADDITIONAL_INFO" as x16, x20."ACTIVITY_ID" as x17, x20."USER_NAME" as x18, x20."MESSAGE" as x19 from "ACTIVITY" x20) x11 inner join (select x21."UPDATED_DATE" as x22, x21."PARENT_REPOSITORY_NAME" as x23, x21."DEFAULT_BRANCH" as x24, x21."DESCRIPTION" as x25, x21."ORIGIN_REPOSITORY_NAME" as x26, x21."ORIGIN_USER_NAME" as x27, x21."PARENT_USER_NAME" as x28, x21."PRIVATE" as x29, x21."REPOSITORY_NAME" as x30, x21."USER_NAME" as x31, x21."REGISTERED_DATE" as x32, x21."LAST_ACTIVITY_DATE" as x33 from "REPOSITORY" x21) x34 on (x11.x18 = x34.x31) and (x11.x15 = x34.x30) where x34.x29 = ? order by x11.x17 desc limit 30) x2 [50000-180]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:624)
	at org.h2.result.ResultTempTable.addRow(ResultTempTable.java:157)
	at org.h2.result.ResultTempTable.addRows(ResultTempTable.java:170)
	at org.h2.result.LocalResult.addRowsToDisk(LocalResult.java:291)
	at org.h2.result.LocalResult.addRow(LocalResult.java:286)
	at org.h2.command.dml.Select.queryFlat(Select.java:544)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:644)
	at org.h2.command.dml.Query.query(Query.java:322)
	at org.h2.command.dml.Query.query(Query.java:290)
	at org.h2.index.ViewIndex.find(ViewIndex.java:284)
	at org.h2.index.ViewIndex.find(ViewIndex.java:177)
	at org.h2.index.BaseIndex.find(BaseIndex.java:127)
	at org.h2.index.IndexCursor.find(IndexCursor.java:159)
	at org.h2.table.TableFilter.next(TableFilter.java:329)
	at org.h2.command.dml.Select.queryFlat(Select.java:532)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:644)
	at org.h2.command.dml.Query.query(Query.java:322)
	at org.h2.command.dml.Query.query(Query.java:290)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:90)
	at org.h2.command.Command.executeQuery(Command.java:197)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:192)
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.build(Invoker.scala:47)
	at scala.slick.jdbc.StatementInvoker.build(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.list(Invoker.scala:39)
	at scala.slick.jdbc.StatementInvoker.list(StatementInvoker.scala:16)
	at service.ActivityService$class.getRecentActivities(ActivityService.scala:31)
	at app.IndexController.getRecentActivities(IndexController.scala:8)
	at app.IndexControllerBase$$anonfun$2.apply(IndexController.scala:24)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)
	at app.ControllerBase.withRouteMultiParams(ControllerBase.scala:21)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)
	at app.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:21)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:74)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:68)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)
	at app.ControllerBase.withRouteMultiParams(ControllerBase.scala:21)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:68)
	at app.ControllerBase.invoke(ControllerBase.scala:21)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)
	at scala.Option.flatMap(Option.scala:170)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:462)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237)
	at app.ControllerBase.runRoutes(ControllerBase.scala:21)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at app.ControllerBase.executeRoutes(ControllerBase.scala:21)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at app.ControllerBase.withResponse(ControllerBase.scala:21)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at app.ControllerBase.withRequest(ControllerBase.scala:21)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at app.ControllerBase.withRequestResponse(ControllerBase.scala:21)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at app.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:21)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at app.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:21)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at app.ControllerBase.withRequest(ControllerBase.scala:21)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at app.ControllerBase.handle(ControllerBase.scala:21)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at app.ControllerBase.doFilter(ControllerBase.scala:55)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at servlet.PluginActionInvokeFilter$$anonfun$doFilter$1.apply(PluginActionInvokeFilter.scala:26)
	at servlet.PluginActionInvokeFilter$$anonfun$doFilter$1.apply(PluginActionInvokeFilter.scala:23)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withTransaction(JdbcBackend.scala:61)
	at servlet.PluginActionInvokeFilter.doFilter(PluginActionInvokeFilter.scala:23)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:27)
	at servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:24)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withTransaction(JdbcBackend.scala:61)
	at servlet.TransactionFilter.doFilter(TransactionFilter.scala:24)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unsynchronized metadata read [1.4.180/3]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:756)
	at org.h2.mvstore.MVStore.getChunkIfFound(MVStore.java:829)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:814)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1860)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:767)
	at org.h2.mvstore.Page.getChildPage(Page.java:252)
	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:467)
	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:468)
	at org.h2.mvstore.MVMap.get(MVMap.java:449)
	at org.h2.mvstore.MVMapConcurrent.put(MVMapConcurrent.java:47)
	at org.h2.store.LobStorageMap.copyLob(LobStorageMap.java:220)
	at org.h2.value.ValueLobDb.link(ValueLobDb.java:248)
	at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:120)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:620)
	... 137 more
```
Is there any way to recover this database?

**Comment by Prajithp** [comment]
Can I get any updates? Its happened again today :(

**Comment by Prajithp** [comment]
BTW, What is the password of h2 gitbucket database? I'm getting "Wrong user name or password [28000-180] 28000/28000 (Help)" in h2 console.

**Comment by takezoe** [comment]
You can connect H2 database with following configuration:
```
JDBC URL: jdbc:h2:~/.gitbucket/data
User Name: sa
Password: sa
```
If your database is broken, try the H2 recovery tool.
http://www.h2database.com/html/advanced.html#using_recover_tool

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
