### ISSUE TITLE
error to connect to gmail

### ISSUE THREAD

**Issue by tkisme** [takezoe/gitbucket#866]
![image](https://cloud.githubusercontent.com/assets/5886048/9155777/4377a736-3ef6-11e5-8be1-b69677d58319.png)
I config it like this but not work

**Comment by takezoe** [comment]
Any error messages? Is it possible to send other mail client?
Check the following page to send mail via Gmail smtp server:
https://support.google.com/mail/answer/78775?hl=en

**Comment by FlYnN91** [comment]
I know I can't connect from any client to gmail until you create app access key

**Comment by McFoggy** [comment]
Of course you can use the google smtp without any app key.
You can find the settings instructions here: https://support.google.com/a/answer/176600?hl=en

**Comment by tkisme** [comment]
I use app access key already, but still cannot work,now l try to debug with source code.

**Comment by tkisme** [comment]
I run it 
```
java -Xmx512M -Xms256M -jar /var/lib/openshift/5543db2d5973cac9290000be/app-root/runtime/repo/gitbucket.war --gitbucket.home=/var/lib/openshift/5543db2d5973cac9290000be/app-root/runtime/repo/../../data/.gitbucket/ --host=127.12.54.129 --port=8080
```
and error is 
```
Notifications Failed.
java.sql.SQLException: You can't operate on a closed Connection!!!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:300)
	at scala.slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:152)
	at scala.slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:389)
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:32)
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.firstOption(Invoker.scala:29)
	at scala.slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
	at gitbucket.core.service.AccountService$class.getAccountByUserName(AccountService.scala:78)
	at gitbucket.core.view.GitBucketHtmlSerializer.gitbucket$core$service$RequestCache$$super$getAccountByUserName(Markdown.scala:111)
	at gitbucket.core.service.RequestCache$$anonfun$getAccountByUserName$1.apply(RequestCache.scala:27)
	at gitbucket.core.service.RequestCache$$anonfun$getAccountByUserName$1.apply(RequestCache.scala:27)
	at gitbucket.core.controller.Context$$anonfun$cache$1$$anonfun$apply$2.apply(ControllerBase.scala:194)
	at scala.Option.getOrElse(Option.scala:121)
	at gitbucket.core.controller.Context$$anonfun$cache$1.apply(ControllerBase.scala:193)
	at gitbucket.core.controller.Context$$anonfun$cache$1.apply(ControllerBase.scala:192)
	at gitbucket.core.util.ControlUtil$.defining(ControlUtil.scala:14)
	at gitbucket.core.controller.Context.cache(ControllerBase.scala:192)
	at gitbucket.core.service.RequestCache$class.getAccountByUserName(RequestCache.scala:26)
	at gitbucket.core.view.GitBucketHtmlSerializer.getAccountByUserName(Markdown.scala:111)
	at gitbucket.core.view.LinkConverter$$anonfun$convertRefsLinks$6.apply(LinkConverter.scala:65)
	at gitbucket.core.view.LinkConverter$$anonfun$convertRefsLinks$6.apply(LinkConverter.scala:64)
	at gitbucket.core.util.Implicits$RichString$$anonfun$replaceBy$1.apply(Implicits.scala:48)
	at gitbucket.core.util.Implicits$RichString$$anonfun$replaceBy$1.apply(Implicits.scala:45)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at gitbucket.core.util.Implicits$RichString.replaceBy(Implicits.scala:45)
	at gitbucket.core.view.LinkConverter$class.convertRefsLinks(LinkConverter.scala:64)
	at gitbucket.core.view.GitBucketHtmlSerializer.convertRefsLinks(Markdown.scala:111)
	at gitbucket.core.view.GitBucketHtmlSerializer.visit(Markdown.scala:201)
	at org.pegdown.ast.TextNode.accept(TextNode.java:51)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:372)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:355)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:372)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:384)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:165)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:372)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:89)
	at org.pegdown.ast.RootNode.accept(RootNode.java:51)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:70)
	at gitbucket.core.view.Markdown$.toHtml(Markdown.scala:57)
	at gitbucket.core.util.Mailer$$anonfun$1$$anonfun$apply$4.apply(Notifier.scala:78)
	at gitbucket.core.util.Mailer$$anonfun$1$$anonfun$apply$4.apply(Notifier.scala:75)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at gitbucket.core.util.Mailer$$anonfun$1.apply(Notifier.scala:75)
	at gitbucket.core.util.Mailer$$anonfun$1.apply(Notifier.scala:74)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:260)
	... 56 more
```

**Comment by McFoggy** [comment]
Is it working now? Did you found any workaround? Is there something wrong in gitbucket ? if not please close the issue, thanks.

**Comment by tkisme** [comment]
Still now working now

**Comment by McFoggy** [comment]
For those using google as a smtp server, you probably need to activate the "[less secure application](https://www.google.com/settings/security/lesssecureapps)" google settings on your account: https://www.google.com/settings/security/lesssecureapps.

Personnaly I had to do it to be able to test with a gmail smtp using SSL.
